spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size=50
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

