spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ingyu.iptime.org:3306/bellbell
    username: root
    password: overcoming
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 028ee7a2f78af06f7872d4aa7cbc1339
            client-secret: mm7VrLqI1fJEXnRQ8EgIcnEZlFy41S2f
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id